package ai.interviewhq.api.experience.controller;
import ai.interviewhq.api.common.exception.PublicApiExceptionHandler;
import ai.interviewhq.api.common.response.ApiCollectionResponse;
import ai.interviewhq.api.question.dto.QuestionSummaryResponse;
import java.util.List; import ai.interviewhq.api.experience.dto.ExperienceResponse; import ai.interviewhq.api.experience.service.ExperienceService; import ai.interviewhq.api.question.service.QuestionService; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest; import org.springframework.boot.test.mock.mockito.MockBean; import org.springframework.context.annotation.Import; import org.springframework.test.web.servlet.MockMvc;
import static org.mockito.Mockito.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@WebMvcTest(ExperienceController.class) @Import(PublicApiExceptionHandler.class)
class ExperienceControllerTest {
 @Autowired MockMvc mvc; @MockBean ExperienceService experiences; @MockBean QuestionService questions;
 @Test void listsExperiences(){when(experiences.list(null,null,"newest")).thenReturn(new ApiCollectionResponse<>(List.of(new ai.interviewhq.api.experience.dto.ExperienceSummaryResponse(7,"Interview","Acme","SWE","L5","Seattle","glassdoor",null,"https://example.com/1",3)),new ApiCollectionResponse.Pagination(25,null,false)));try{mvc.perform(get("/api/v1/experiences")).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].id").value(7)).andExpect(jsonPath("$.pagination.limit").value(25));}catch(Exception e){throw new AssertionError(e);}}
 @Test void listsExperiencesWithCursor(){when(experiences.list(10,"opaque","oldest")).thenReturn(new ApiCollectionResponse<>(List.of(),new ApiCollectionResponse.Pagination(10,"next",true)));try{mvc.perform(get("/api/v1/experiences").param("limit","10").param("cursor","opaque").param("sort","oldest")).andExpect(status().isOk()).andExpect(jsonPath("$.pagination.nextCursor").value("next"));}catch(Exception e){throw new AssertionError(e);}}
 @Test void getsExperience(){when(experiences.find(7)).thenReturn(new ExperienceResponse(7,"glassdoor","Interview",null,null,null,null,"Acme","SWE",null,"Seattle",null,3,null));try{mvc.perform(get("/api/v1/experiences/7")).andExpect(status().isOk()).andExpect(jsonPath("$.item.id").value(7)).andExpect(jsonPath("$.item.company").value("Acme"));}catch(Exception e){throw new AssertionError(e);}}
 @Test void listsExperienceQuestions(){when(experiences.find(7)).thenReturn(new ExperienceResponse(7,"glassdoor","Interview",null,null,null,null,"Acme","SWE",null,"Seattle",null,3,null));when(questions.byExperience(7,null,null)).thenReturn(new ApiCollectionResponse<>(List.of(new QuestionSummaryResponse(1,7,"Q",List.of("Coding"),.9f,null,null,null,"Acme","SWE","glassdoor")),new ApiCollectionResponse.Pagination(25,null,false)));try{mvc.perform(get("/api/v1/experiences/7/questions")).andExpect(status().isOk()).andExpect(jsonPath("$.items[0].id").value(1));}catch(Exception e){throw new AssertionError(e);}}
 @Test void rejectsInvalidId(){try{mvc.perform(get("/api/v1/experiences/0")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.error.code").value("VALIDATION_ERROR"));verifyNoInteractions(experiences);}catch(Exception e){throw new AssertionError(e);}}
}
